############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Services"
pageRef = "/services"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Services"
pageRef = "/services"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
